### ISSUE TITLE
Composite Builds

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#175]
Checking possibilities of moving to composite builds

Note: Without hacky custom plugin
Note 2: Think how SubMob libraries will adapt it

**Comment by oanamariabalaita** [comment]
In conclusion adopting composite builds is not suitable because SubMob libraries can not override the project dependencies with their own dependencies. In addition, not worth to create and integrate a dummy plugin just for dependencies. 

Closing the ticket and following and expecting `buildSrc` to become a composite build in the next Gradle releases.
