### ISSUE TITLE
Implement different appId for Google and Huawei flavours

### ISSUE THREAD

**Issue by mustafaozhan** [Oztechan/CCC#374]

**Comment by oanamariabalaita** [comment]
Configuration and signing considerations for distributing the app on Huawei devices that still having Google Play Services

###### The smallest heading
## The second largest heading

> Text that is a quote

Since the intended behaviour is to have different apps in case CCC is installed from both stores, the `applicationId` should be different for `huawei` and `google` flavors.


ℹ️ You are advised to use a key different from the signature key. If you do not submit an upload key, you need to use your signature key as the upload key. [Source](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-appsigning-releasedapp-0000001051818319)




If your project needs to support different app packages for different channels, the package name needs to vary depending on the channel. Change the package name under productFlavor in the build.gradle file in the app directory.

Source: [Huawei Docs](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-config-flavor-android-0000001057944603)

        "package_name": "xxx.huawei"
        
https://github.com/abusuioc/from-gms-to-hms

Source: [here](https://medium.com/mobindustry/how-we-published-a-large-ecommerce-app-on-the-huawei-appgallery-store-50fd257dbc8e)

we added the .huawei, applicationIdSuffix, as it’s a requirement of AppGallery if you plan to use HMS in your app.

**Comment by oanamariabalaita** [comment]
Configuration and signing considerations for distributing the app on Huawei devices that still having Google Play Services

Since the intended behaviour is to have different apps in case CCC is installed from both stores, the `applicationId` should be different for `huawei` and `google` flavors. 

Sources: [Google Docs](https://developer.android.com/studio/build/build-variants) , [Huawei Docs](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-config-flavor-android-0000001057944603), [Production app use case](https://medium.com/mobindustry/how-we-published-a-large-ecommerce-app-on-the-huawei-appgallery-store-50fd257dbc8e)

> Moreover, Huawei introduced restrictions for application ID of applications that enable in-app purchases through the AppGallery – application ID must end with .huawei, otherwise the purchases in the application will not be working.

Sources: [source1](https://www.ackee.agency/blog/application-distribution-huawei-appgallery), [source2](https://i.ibb.co/ZHKcCdW/Screenshot-2.png)

For security reasons is advised to have different signing keys for releasing the app in both stores.

ℹ️ You are advised to use a key different from the signature key. If you do not submit an upload key, you need to use your signature key as the upload key. [Huawei Docs](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-appsigning-releasedapp-0000001051818319)
