### ISSUE TITLE
Base iOS instructions fail with Xcode 13 (on M1)

### ISSUE THREAD

**Issue by mevdev** [Oztechan/CCC#626]
## Description

OS: Monterey 12.1
Android Studio: Bumblebee 2021.1.1 Patch 2
Xcode: Version 13.3 (13E113)
Machine: 2021 16" M1 Pro

The instructions to run in the terminal from Android Studio didn't work until I added the JDK to my zsh ($HOME/.zshrc)
`export JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/Contents/Home`

The commands worked after adding this, but in Xcode it gives an error:

`> The project must have a target for at least one of the following platforms: ios_simulator_arm64.`

This seems like it is an M1 problem where the binary is being built for x86 simulator only.

**Comment by mustafaozhan** [comment]
@mevdev Sorry it took so long, I was giving my all focus to publish the app in App Store, which is finally done 🙂 

I have updated the dependencies and the structure a lot, together with the `README.md`, I tried in my local now, and it works fine, can you try also in your `M1` device ? I can not verify it since I don't have one.
